### ISSUE TITLE
在 telegram 中无法发送过长的图片

### ISSUE THREAD

**Issue by bysansheng** [MeetWq/nonebot-plugin-remake#17]
![image](https://github.com/user-attachments/assets/eb6cc739-4377-4dfd-beb9-6f5117975451)
![image](https://github.com/user-attachments/assets/263b739d-3f87-4656-be58-25e76c4d08e2)
![image](https://github.com/user-attachments/assets/dc96a29f-0cd4-4408-a371-14451e81e9e2)

**Comment by MeetWq** [comment]
虽然但是，发错地方了

**Comment by MeetWq** [comment]
我试了一下，telegram 中图片很容易发不出去，我改成图片发不了的时候以文件形式发送了
