### ISSUE TITLE
作者君在utils.py中打错了一个字符，引起了一个bug

### ISSUE THREAD

**Issue by ziru-w** [MeetWq/nonebot-plugin-remake#3]
![image](https://user-images.githubusercontent.com/77319678/154655701-8ac5f1f0-ebff-469c-81be-e9ac45dd3d26.png)

如图，cond.replace('AEVT', 'AVT')) \应该是cond.replace('AEVT', 'EVT')) \，否则当选择神秘盒子天赋后，程序将报错，显示没有AVT属性。

**Comment by MeetWq** [comment]
我加了 `AVT` 属性防报错
`AEVT` 应该是触发过的事件，但这个插件并没有记录重开历史，所以这个参数并没有什么用

**Comment by ziru-w** [comment]
其实我不是很懂re.compile(),所以其实没看懂这一大串。不过我修改概率列表，选择到神秘盒子天赋后，确实报错了，让后改这里改成EVT就好了。报错信息如下，AttributeError: 'Property' object has no attribute 'AVT'。

**Comment by MeetWq** [comment]
`EVT` 和 `AVT` 在原项目里是不同的，你这么改问题也不大，因为 `AVT` 比较少

**Comment by ziru-w** [comment]
好的
![PWP2NCYHK$1{ 5B~{X3{`V2](https://user-images.githubusercontent.com/77319678/154809216-5c415aec-9df3-4691-9c8d-d768801e3bff.png)
