### ISSUE TITLE
可以做成图片的形式吗转发聊天记录阅读要翻好久

### ISSUE THREAD

**Issue by FlashKiana** [MeetWq/nonebot-plugin-remake#7]
![image](https://user-images.githubusercontent.com/24948734/196024896-159ca9ce-9d27-4b9d-8a08-b1a2756ab2dd.png)
就像这样

**Comment by lintonxue00** [comment]
聊天记录也挺不错，做成图片还要考虑服务器性能

**Comment by MeetWq** [comment]
新版做成图片了，有什么建议欢迎反馈
